language: ruby
rvm:
- 2.1.5
deploy:
  provider: heroku
  app: dead-cockroach
  api_key:
    secure: "DJ1vueLatpW+6XNK2/zTCQFuASA4sGs0h6VIzXa3rZV5RqY4/AGlzAP0bCHIQjPRsG9Amz0YrKIwmbWQLqJn2si3LBs2kZ+2/8xEJ7LBbn+Y03oZbk3eb9ewjWzrp3ER/EUBjQ/Y2oFWXUa0RvmlCzUXxQF0IT/3btQcQkt5xV4="
